plugins {
  id("com.android.application")
  kotlin("android")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(25)
    targetSdkVersion(25)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
  }
}
dependencies {
  androidTestImplementation(project(":module03:module24:module05"))
  androidTestImplementation(project(":module05:module05"))
  androidTestImplementation(project(":module05:module06:module2"))
  androidTestImplementation(project(":module05:module14:module10"))
  androidTestImplementation(project(":module05:module27:module3"))
  androidTestImplementation(project(":module05:module34:module5"))
  androidTestImplementation(project(":module06:module05:module03:module2"))
  androidTestImplementation(project(":module06:module05:module05:module2"))
  androidTestImplementation(project(":module06:module05:module23:module2"))
  androidTestImplementation(project(":module06:module05:module26:module2"))
  androidTestImplementation(project(":module06:module10:module1"))
  androidTestImplementation(project(":module06:module16:module09"))
  androidTestImplementation(project(":module07:module041:module5"))
  androidTestImplementation(project(":module07:module050:module4"))
  androidTestImplementation(project(":module07:module094:module1"))
  androidTestImplementation(project(":module07:module147:module3"))
  androidTestImplementation(project(":module07:module148:module08"))
  androidTestImplementation(project(":module07:module166:module1"))
  androidTestImplementation(project(":module07:module195:module02:module4:module07"))
  androidTestImplementation(project(":module07:module195:module02:module7:module5"))
  androidTestImplementation(project(":module07:module195:module09:module1"))
  androidTestImplementation(project(":module07:module209:module2"))
  androidTestImplementation(project(":module07:module211:module4"))
  androidTestImplementation(project(":module07:module212:module4"))
  androidTestImplementation(project(":module07:module224:module4"))
  androidTestImplementation(project(":module07:module231:module3"))
  androidTestImplementation(project(":module07:module242:module3"))
  androidTestImplementation(project(":module07:module244:module3"))
  androidTestImplementation(project(":module07:module244:module5"))
  androidTestImplementation(project(":module07:module282:module4"))
  androidTestImplementation(project(":module07:module301:module2"))
  androidTestImplementation(project(":module07:module306:module3"))
  androidTestImplementation(project(":module07:module308:module2"))
  androidTestImplementation(project(":module07:module302:module1"))
  androidTestImplementation(project(":module07:module317:module1"))
  androidTestImplementation(project(":module07:module327:module3"))
  androidTestImplementation(project(":module07:module333:module4"))
  androidTestImplementation(project(":module07:module350:module06"))
  androidTestImplementation(project(":module07:module356:module1:module4"))
  androidTestImplementation(project(":module07:module356:module3:module3"))
  androidTestImplementation(project(":module07:module364:module4"))
  androidTestImplementation(project(":module07:module366:module5"))
  androidTestImplementation(project(":module07:module382:module5"))
  androidTestImplementation(project(":module07:module476:module3"))
  androidTestImplementation(project(":module07:module512:module5"))
  androidTestImplementation(project(":module07:module515:module4"))
  androidTestImplementation(project(":module07:module526:module1:module3"))
  androidTestImplementation(project(":module07:module536:module3"))
  androidTestImplementation(project(":module07:module538:module1"))
  androidTestImplementation(project(":module07:module539:module1"))
  androidTestImplementation(project(":module08:module11:module01:module1:module4"))
  androidTestImplementation(project(":module08:module11:module01:module4:module2"))
  androidTestImplementation(project(":module08:module11:module01:module5:module3"))
  androidTestImplementation(project(":module08:module11:module01:module6:module3"))
  androidTestImplementation(project(":module08:module11:module06:module3"))
  androidTestImplementation(project(":module08:module11:module07:module3"))
  androidTestImplementation(project(":module08:module11:module09:module2"))
  androidTestImplementation(project(":module08:module11:module10:module3"))
  androidTestImplementation(project(":module08:module11:module11:module4"))
  androidTestImplementation(project(":module08:module11:module13:module3"))
  androidTestImplementation(project(":module08:module11:module16:module3"))
  androidTestImplementation(project(":module08:module11:module15:module2:module3"))
  androidTestImplementation(project(":module08:module11:module15:module3:module3"))
  androidTestImplementation(project(":module08:module11:module15:module4:module2"))
  androidTestImplementation(project(":module08:module11:module18:module2:module3"))
  androidTestImplementation(project(":module08:module29:module2"))
  androidTestImplementation(project(":module08:module36:module4"))
  androidTestImplementation(project(":module08:module61:module5"))
  androidTestImplementation(project(":module11"))
  androidTestImplementation(project(":module15:module2"))
  androidTestImplementation(project(":module23:module01:module12:module2"))
  androidTestImplementation(project(":module23:module01:module35"))
  androidTestImplementation(project(":module23:module01:module43"))
  androidTestImplementation(project(":module23:module01:module48"))
  androidTestImplementation(project(":module23:module07:module12:module3"))
  androidTestImplementation(project(":module23:module07:module31"))
  androidTestImplementation(project(":module23:module07:module32"))
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  androidTestImplementation("androidx.test.espresso:espresso-contrib:3.3.0")
  androidTestImplementation("androidx.test.espresso:espresso-core:3.3.0")
  androidTestImplementation("androidx.test.espresso:espresso-idling-resource:3.3.0")
  androidTestImplementation("androidx.test:rules:1.4.0")
  androidTestImplementation("androidx.test:runner:1.4.0")
  androidTestImplementation("com.google.truth:truth:1.1.3")
  androidTestImplementation("junit:junit:4.13.2")
  androidTestImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module03:module24:module06"))
  implementation(project(":module07:module313:module2"))
  implementation(project(":module07:module505:module1"))
  implementation(project(":module23:module01:module23"))
  implementation(project(":module23:module01:module31:module1"))
  implementation(project(":module23:module01:module32"))
  implementation(project(":module23:module01:module41"))
  implementation(project(":module23:module01:module45"))
  implementation(project(":module23:module01:module53"))
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
}
