plugins {
  id("com.android.library")
  kotlin("android")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
    androidResources = true
    compose = true
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  androidTestImplementation("androidx.compose.ui:ui-test-junit4:1.2.0-alpha07")
  api(project(":module07:module175:module1"))
  api(project(":module07:module403:module4:module2"))
  api(project(":module07:module438:module1"))
  api(project(":module20:module3:module6"))
  api("com.google.dagger:dagger:2.39.1")
  api("javax.inject:javax.inject:1")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module07:module023:module2:module1"))
  implementation(project(":module07:module024:module5"))
  implementation(project(":module07:module066:module6"))
  implementation(project(":module07:module082:module2"))
  implementation(project(":module07:module114:module2"))
  implementation(project(":module07:module139"))
  implementation(project(":module07:module146:module3"))
  implementation(project(":module07:module151:module1"))
  implementation(project(":module07:module159:module1"))
  implementation(project(":module07:module166:module2"))
  implementation(project(":module07:module178"))
  implementation(project(":module07:module195:module02:module4:module10"))
  implementation(project(":module07:module195:module02:module5:module6"))
  implementation(project(":module07:module195:module06:module1"))
  implementation(project(":module07:module195:module08:module1"))
  implementation(project(":module07:module195:module09:module3"))
  implementation(project(":module07:module208:module8"))
  implementation(project(":module07:module215"))
  implementation(project(":module07:module243:module8"))
  implementation(project(":module07:module258:module3"))
  implementation(project(":module07:module284:module3"))
  implementation(project(":module07:module288"))
  implementation(project(":module07:module314:module1"))
  implementation(project(":module07:module329:module1"))
  implementation(project(":module07:module341:module1"))
  implementation(project(":module07:module342:module1"))
  implementation(project(":module07:module338:module1"))
  implementation(project(":module07:module371:module4"))
  implementation(project(":module07:module390:module4"))
  implementation(project(":module07:module393:module2"))
  implementation(project(":module07:module403:module1:module5"))
  implementation(project(":module07:module426"))
  implementation(project(":module07:module425:module1"))
  implementation(project(":module07:module428:module4"))
  implementation(project(":module07:module534:module1"))
  implementation(project(":module07:module549:module3"))
  implementation(project(":module07:module546:module1"))
  implementation(project(":module07:module550:module1"))
  implementation(project(":module07:module554:module1"))
  implementation(project(":module07:module565:module2"))
  implementation(project(":module07:module566:module2"))
  implementation(project(":module07:module567:module2"))
  implementation(project(":module08:module06:module3"))
  implementation(project(":module08:module21:module2"))
  implementation(project(":module08:module30"))
  implementation(project(":module08:module38:module15:module2"))
  implementation(project(":module14:module2:module2"))
  implementation(project(":module16:module061:module1"))
  implementation(project(":module16:module092:module1"))
  implementation(project(":module20:module1:module1:module4"))
  implementation(project(":module20:module1:module3:module2"))
  implementation(project(":module20:module1:module5:module1"))
  implementation(project(":module20:module1:module6:module1"))
  implementation(project(":module20:module2:module01:module3"))
  implementation(project(":module20:module2:module06:module3"))
  implementation(project(":module20:module2:module07:module2"))
  implementation(project(":module20:module2:module08:module6"))
  implementation(project(":module20:module2:module09:module3"))
  implementation(project(":module20:module2:module11:module4"))
  implementation(project(":module20:module2:module13:module3"))
  implementation(project(":module20:module2:module15:module3"))
  implementation(project(":module20:module2:module18:module5"))
  implementation("androidx.compose.foundation:foundation:1.2.0-alpha07")
  implementation("ca.barrenechea.header-decor:header-decor:0.3-cash01")
  implementation("io.reactivex.rxjava2:rxjava:2.2.20")
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
  testImplementation(project(":module07:module068"))
  testImplementation(project(":module07:module108:module4"))
  testImplementation(project(":module07:module128"))
  testImplementation(project(":module07:module132:module7"))
  testImplementation(project(":module07:module150:module3"))
  testImplementation(project(":module07:module195:module06:module2"))
  testImplementation(project(":module07:module213:module7"))
  testImplementation(project(":module07:module224:module7"))
  testImplementation(project(":module07:module324:module1"))
  testImplementation(project(":module07:module401"))
  testImplementation(project(":module07:module447:module2"))
  testImplementation(project(":module07:module464:module7"))
  testImplementation(project(":module07:module517:module4"))
  testImplementation(project(":module07:module518:module11"))
  testImplementation(project(":module07:module522:module1"))
  testImplementation(project(":module07:module547:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation(project(":module16:module025:module1"))
  testImplementation(project(":module16:module061:module1"))
  testImplementation(project(":module20:module1:module2:module2"))
  testImplementation(project(":module20:module2:module08:module1"))
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.0")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.mockito:mockito-core:3.12.4")
  testImplementation("org.robolectric:robolectric:4.7.3")
}
