plugins {
  id("com.android.library")
  id("org.jetbrains.kotlin.android")
  id("org.jetbrains.kotlin.kapt")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
    androidResources = true
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  api(project(":module07:module004:module1"))
  api(project(":module07:module012"))
  api(project(":module07:module014:module3"))
  api(project(":module07:module085:module1"))
  api(project(":module07:module084:module3"))
  api(project(":module07:module097:module4"))
  api(project(":module07:module096:module1"))
  api(project(":module07:module099"))
  api(project(":module07:module109:module3"))
  api(project(":module07:module106:module5"))
  api(project(":module07:module130:module4"))
  api(project(":module07:module178"))
  api(project(":module07:module235:module1"))
  api(project(":module07:module244:module7"))
  api(project(":module07:module258:module3"))
  api(project(":module07:module396:module1"))
  api(project(":module07:module395:module2"))
  api(project(":module07:module455:module4"))
  api(project(":module07:module508"))
  api(project(":module07:module542:module2"))
  api(project(":module07:module562:module2"))
  api("com.google.dagger:dagger:2.39.1")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module01:module07"))
  implementation(project(":module01:module12:module3"))
  implementation(project(":module01:module14"))
  implementation(project(":module01:module19"))
  implementation(project(":module06:module02:module3"))
  implementation(project(":module06:module19:module3:module2"))
  implementation(project(":module07:module069:module3"))
  implementation(project(":module07:module074:module3"))
  implementation(project(":module07:module077:module7"))
  implementation(project(":module07:module089:module6"))
  implementation(project(":module07:module102"))
  implementation(project(":module07:module152:module1"))
  implementation(project(":module07:module150:module2"))
  implementation(project(":module07:module159:module1"))
  implementation(project(":module07:module157:module2"))
  implementation(project(":module07:module175:module1"))
  implementation(project(":module07:module176:module6"))
  implementation(project(":module07:module194"))
  implementation(project(":module07:module195:module06:module1"))
  implementation(project(":module07:module195:module07:module3"))
  implementation(project(":module07:module195:module09:module3"))
  implementation(project(":module07:module195:module11:module1"))
  implementation(project(":module07:module210:module1"))
  implementation(project(":module07:module263:module5"))
  implementation(project(":module07:module288"))
  implementation(project(":module07:module297:module3"))
  implementation(project(":module07:module329:module1"))
  implementation(project(":module07:module338:module1"))
  implementation(project(":module07:module383:module3"))
  implementation(project(":module07:module406:module4"))
  implementation(project(":module07:module411:module3"))
  implementation(project(":module07:module420:module2"))
  implementation(project(":module07:module431:module1"))
  implementation(project(":module07:module440:module5"))
  implementation(project(":module07:module505:module1"))
  implementation(project(":module07:module507:module1"))
  implementation(project(":module07:module514:module5"))
  implementation(project(":module07:module517:module3"))
  implementation(project(":module07:module527"))
  implementation(project(":module07:module529:module1"))
  implementation(project(":module07:module528:module2"))
  implementation(project(":module07:module543:module3"))
  implementation(project(":module07:module549:module3"))
  implementation(project(":module07:module546:module1"))
  implementation(project(":module16:module011:module2"))
  implementation(project(":module16:module061:module1"))
  implementation("com.google.android.material:material:1.2.1")
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
  kapt("com.google.dagger:dagger-compiler:2.39.1")
  testImplementation(project(":module07:module005:module9"))
  testImplementation(project(":module07:module068"))
  testImplementation(project(":module07:module069:module3"))
  testImplementation(project(":module07:module128"))
  testImplementation(project(":module07:module132:module7"))
  testImplementation(project(":module07:module147:module9"))
  testImplementation(project(":module07:module150:module3"))
  testImplementation(project(":module07:module213:module1"))
  testImplementation(project(":module07:module213:module7"))
  testImplementation(project(":module07:module224:module7"))
  testImplementation(project(":module07:module324:module1"))
  testImplementation(project(":module07:module325:module1"))
  testImplementation(project(":module07:module386"))
  testImplementation(project(":module07:module411:module4"))
  testImplementation(project(":module07:module419"))
  testImplementation(project(":module07:module447:module2"))
  testImplementation(project(":module07:module464:module7"))
  testImplementation(project(":module07:module517:module4"))
  testImplementation(project(":module07:module518:module11"))
  testImplementation(project(":module07:module528:module3"))
  testImplementation(project(":module07:module532"))
  testImplementation(project(":module07:module542:module3"))
  testImplementation(project(":module07:module547:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation("androidx.test:runner:1.4.0")
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.mockito:mockito-core:3.12.4")
  testImplementation("org.robolectric:robolectric:4.7.3")
}
