plugins {
  id("com.android.library")
  id("org.jetbrains.kotlin.android")
  id("org.jetbrains.kotlin.kapt")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = true
    androidResources = true
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  api(project(":module06:module05:module05:module5"))
  api(project(":module06:module05:module13:module3"))
  api(project(":module06:module07:module4"))
  api(project(":module06:module08:module4"))
  api(project(":module07:module005:module8"))
  api(project(":module07:module043"))
  api(project(":module07:module067:module1"))
  api(project(":module07:module072:module3"))
  api(project(":module07:module109:module3"))
  api(project(":module07:module112"))
  api(project(":module07:module127"))
  api(project(":module07:module145"))
  api(project(":module07:module147:module8"))
  api(project(":module07:module161:module1"))
  api(project(":module07:module175:module1"))
  api(project(":module07:module195:module06:module1"))
  api(project(":module07:module213:module6"))
  api(project(":module07:module219:module4"))
  api(project(":module07:module223"))
  api(project(":module07:module235:module1"))
  api(project(":module07:module247:module2"))
  api(project(":module07:module257:module3"))
  api(project(":module07:module291:module1"))
  api(project(":module07:module298:module7"))
  api(project(":module07:module302:module6"))
  api(project(":module07:module368:module6"))
  api(project(":module07:module384:module3"))
  api(project(":module07:module399"))
  api(project(":module07:module411:module3"))
  api(project(":module07:module415:module4"))
  api(project(":module07:module418"))
  api(project(":module07:module424:module2"))
  api(project(":module07:module463:module2"))
  api(project(":module07:module464:module6"))
  api(project(":module07:module487"))
  api(project(":module07:module489:module4"))
  api(project(":module07:module502:module2"))
  api(project(":module07:module501:module1"))
  api(project(":module07:module549:module3"))
  api(project(":module07:module546:module1"))
  api("com.google.dagger:dagger:2.39.1")
  api("io.reactivex.rxjava2:rxjava:2.2.20")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module01:module01"))
  implementation(project(":module06:module01:module3"))
  implementation(project(":module06:module07:module4"))
  implementation(project(":module06:module19:module3:module2"))
  implementation(project(":module07:module025:module6"))
  implementation(project(":module07:module084:module3"))
  implementation(project(":module07:module099"))
  implementation(project(":module07:module108:module4"))
  implementation(project(":module07:module157:module2"))
  implementation(project(":module07:module194"))
  implementation(project(":module07:module195:module09:module3"))
  implementation(project(":module07:module264:module6"))
  implementation(project(":module07:module403:module1:module5"))
  implementation(project(":module07:module420:module2"))
  implementation(project(":module07:module437:module2"))
  implementation(project(":module07:module445:module1"))
  implementation(project(":module07:module528:module2"))
  implementation(project(":module07:module535:module3"))
  implementation(project(":module07:module569"))
  implementation(project(":module16:module011:module2"))
  implementation(project(":module16:module061:module1"))
  implementation(project(":module16:module092:module1"))
  implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
  kapt("com.google.dagger:dagger-compiler:2.39.1")
  testImplementation(project(":module07:module005:module9"))
  testImplementation(project(":module07:module013:module5"))
  testImplementation(project(":module07:module025:module1"))
  testImplementation(project(":module07:module128"))
  testImplementation(project(":module07:module150:module3"))
  testImplementation(project(":module07:module175:module2"))
  testImplementation(project(":module07:module195:module06:module2"))
  testImplementation(project(":module07:module324:module1"))
  testImplementation(project(":module07:module401"))
  testImplementation(project(":module07:module411:module4"))
  testImplementation(project(":module07:module419"))
  testImplementation(project(":module07:module463:module3"))
  testImplementation(project(":module07:module467:module5"))
  testImplementation(project(":module07:module517:module4"))
  testImplementation(project(":module07:module518:module11"))
  testImplementation(project(":module07:module522:module1"))
  testImplementation(project(":module07:module532"))
  testImplementation(project(":module07:module547:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation(project(":module07:module561:module1"))
  testImplementation(project(":module16:module011:module2"))
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.7.20")
  testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.0")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.mockito:mockito-core:3.12.4")
  testImplementation("org.robolectric:robolectric:4.7.3")
}
