plugins {
  id("com.android.library")
  kotlin("android")
  id("org.jetbrains.kotlin.kapt")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
    androidResources = true
    compose = true
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  androidTestImplementation("androidx.compose.ui:ui-test-junit4:1.2.0-alpha07")
  api(project(":module07:module016:module5"))
  api(project(":module07:module025:module6"))
  api(project(":module07:module085:module1"))
  api(project(":module07:module118:module3"))
  api(project(":module07:module130:module4"))
  api(project(":module07:module258:module3"))
  api(project(":module07:module267:module4"))
  api(project(":module07:module271:module6"))
  api(project(":module07:module273:module3"))
  api(project(":module07:module415:module4"))
  api(project(":module08:module11:module01:module7:module5"))
  api(project(":module08:module27:module1"))
  api(project(":module08:module27:module3"))
  api(project(":module08:module52:module7"))
  api(project(":module16:module028:module1"))
  api("com.google.dagger:dagger:2.39.1")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module01:module01"))
  implementation(project(":module01:module19"))
  implementation(project(":module06:module02:module3"))
  implementation(project(":module06:module07:module4"))
  implementation(project(":module07:module070"))
  implementation(project(":module07:module077:module7"))
  implementation(project(":module07:module102"))
  implementation(project(":module07:module127"))
  implementation(project(":module07:module139"))
  implementation(project(":module07:module142:module2"))
  implementation(project(":module07:module152:module1"))
  implementation(project(":module07:module154:module6"))
  implementation(project(":module07:module178"))
  implementation(project(":module07:module179:module5"))
  implementation(project(":module07:module195:module02:module5:module6"))
  implementation(project(":module07:module195:module05:module2:module1"))
  implementation(project(":module07:module195:module06:module1"))
  implementation(project(":module07:module195:module09:module3"))
  implementation(project(":module07:module195:module10:module2:module4"))
  implementation(project(":module07:module213:module6"))
  implementation(project(":module07:module218:module2"))
  implementation(project(":module07:module233:module1"))
  implementation(project(":module07:module264:module6"))
  implementation(project(":module07:module269"))
  implementation(project(":module07:module270:module4"))
  implementation(project(":module07:module271:module6"))
  implementation(project(":module07:module276:module4"))
  implementation(project(":module07:module277:module1"))
  implementation(project(":module07:module288"))
  implementation(project(":module07:module290:module3"))
  implementation(project(":module07:module291:module1"))
  implementation(project(":module07:module311"))
  implementation(project(":module07:module316:module1"))
  implementation(project(":module07:module346:module3"))
  implementation(project(":module07:module388:module4"))
  implementation(project(":module07:module440:module5"))
  implementation(project(":module07:module505:module1"))
  implementation(project(":module07:module546:module1"))
  implementation(project(":module07:module557"))
  implementation(project(":module07:module554:module1"))
  implementation(project(":module07:module561:module1"))
  implementation(project(":module07:module565:module2"))
  implementation(project(":module07:module569"))
  implementation(project(":module08:module12:module05:module1"))
  implementation(project(":module16:module061:module1"))
  implementation(project(":module16:module067:module1"))
  implementation(project(":module16:module092:module1"))
  implementation("androidx.compose.foundation:foundation:1.2.0-alpha07")
  implementation("ca.barrenechea.header-decor:header-decor:0.3-cash01")
  implementation("com.google.android.material:material:1.2.1")
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
  kapt("com.google.dagger:dagger-compiler:2.39.1")
  testImplementation(project(":module07:module128"))
  testImplementation(project(":module07:module132:module7"))
  testImplementation(project(":module07:module147:module9"))
  testImplementation(project(":module07:module150:module3"))
  testImplementation(project(":module07:module175:module2"))
  testImplementation(project(":module07:module213:module7"))
  testImplementation(project(":module07:module316:module1"))
  testImplementation(project(":module07:module325:module1"))
  testImplementation(project(":module07:module401"))
  testImplementation(project(":module07:module411:module4"))
  testImplementation(project(":module07:module447:module2"))
  testImplementation(project(":module07:module463:module3"))
  testImplementation(project(":module07:module467:module1"))
  testImplementation(project(":module07:module464:module7"))
  testImplementation(project(":module07:module468:module4"))
  testImplementation(project(":module07:module517:module4"))
  testImplementation(project(":module07:module518:module11"))
  testImplementation(project(":module07:module522:module1"))
  testImplementation(project(":module07:module547:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.robolectric:robolectric:4.7.3")
}
