plugins {
  id("com.android.application")
  id("org.jetbrains.kotlin.android")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(25)
    targetSdkVersion(25)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
  }
}
dependencies {
  androidTestImplementation(project(":module01:module12:module1"))
  androidTestImplementation(project(":module06:module05:module21:module2"))
  androidTestImplementation(project(":module07:module094:module1"))
  androidTestImplementation(project(":module07:module112"))
  androidTestImplementation(project(":module07:module148:module08"))
  androidTestImplementation(project(":module07:module166:module1"))
  androidTestImplementation(project(":module07:module195:module02:module5:module5"))
  androidTestImplementation(project(":module07:module208:module4"))
  androidTestImplementation(project(":module07:module211:module4"))
  androidTestImplementation(project(":module07:module212:module4"))
  androidTestImplementation(project(":module07:module293:module4"))
  androidTestImplementation(project(":module07:module294:module4"))
  androidTestImplementation(project(":module07:module317:module1"))
  androidTestImplementation(project(":module07:module411:module4"))
  androidTestImplementation(project(":module07:module428:module2"))
  androidTestImplementation(project(":module07:module458:module3"))
  androidTestImplementation(project(":module07:module463:module2"))
  androidTestImplementation(project(":module07:module467:module1"))
  androidTestImplementation(project(":module07:module472:module2"))
  androidTestImplementation(project(":module07:module476:module3"))
  androidTestImplementation(project(":module07:module512:module5"))
  androidTestImplementation(project(":module07:module538:module1"))
  androidTestImplementation(project(":module07:module541:module1"))
  androidTestImplementation(project(":module08:module06:module2"))
  androidTestImplementation(project(":module08:module25:module5:module4"))
  androidTestImplementation(project(":module08:module38:module04:module7"))
  androidTestImplementation(project(":module08:module38:module05:module5"))
  androidTestImplementation(project(":module08:module38:module06:module4"))
  androidTestImplementation(project(":module08:module38:module07:module4"))
  androidTestImplementation(project(":module08:module38:module08:module3"))
  androidTestImplementation(project(":module08:module38:module09:module4"))
  androidTestImplementation(project(":module08:module38:module11:module2"))
  androidTestImplementation(project(":module08:module38:module13:module7"))
  androidTestImplementation(project(":module08:module40:module3"))
  androidTestImplementation(project(":module08:module46:module2"))
  androidTestImplementation(project(":module08:module55:module3"))
  androidTestImplementation(project(":module08:module61:module5"))
  androidTestImplementation(project(":module11"))
  androidTestImplementation(project(":module15:module2"))
  androidTestImplementation(project(":module16:module068:module1"))
  androidTestImplementation(project(":module19:module2:module02:module4"))
  androidTestImplementation(project(":module19:module2:module03:module2"))
  androidTestImplementation(project(":module19:module2:module05:module3"))
  androidTestImplementation(project(":module19:module2:module04:module1"))
  androidTestImplementation(project(":module19:module2:module04:module5"))
  androidTestImplementation(project(":module19:module2:module06:module2"))
  androidTestImplementation(project(":module19:module2:module08:module4"))
  androidTestImplementation(project(":module19:module2:module12:module3"))
  androidTestImplementation(project(":module19:module2:module14:module5"))
  androidTestImplementation(project(":module19:module2:module16:module1"))
  androidTestImplementation(project(":module19:module2:module17:module1"))
  androidTestImplementation(project(":module19:module2:module18:module7"))
  androidTestImplementation(project(":module19:module2:module19:module2"))
  androidTestImplementation(project(":module19:module2:module20:module5"))
  androidTestImplementation(project(":module19:module2:module22:module4"))
  androidTestImplementation(project(":module19:module2:module23:module2"))
  androidTestImplementation(project(":module19:module2:module24:module4"))
  androidTestImplementation(project(":module19:module2:module26:module2"))
  androidTestImplementation(project(":module19:module2:module30:module4"))
  androidTestImplementation(project(":module19:module2:module33:module3"))
  androidTestImplementation(project(":module19:module2:module36:module4"))
  androidTestImplementation(project(":module19:module2:module34:module5"))
  androidTestImplementation(project(":module19:module2:module39:module2"))
  androidTestImplementation(project(":module19:module2:module40:module2"))
  androidTestImplementation(project(":module19:module2:module43:module4"))
  androidTestImplementation(project(":module19:module2:module46:module2"))
  androidTestImplementation(project(":module19:module2:module47:module4"))
  androidTestImplementation(project(":module19:module5:module2:module1"))
  androidTestImplementation(project(":module23:module10:module5"))
  androidTestImplementation(project(":module23:module07:module32"))
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  androidTestImplementation("androidx.test.espresso:espresso-contrib:3.3.0")
  androidTestImplementation("androidx.test.espresso:espresso-core:3.3.0")
  androidTestImplementation("androidx.test.espresso:espresso-idling-resource:3.3.0")
  androidTestImplementation("androidx.test:rules:1.4.0")
  androidTestImplementation("androidx.test:runner:1.4.0")
  androidTestImplementation("com.google.truth:truth:1.1.3")
  androidTestImplementation("junit:junit:4.13.2")
  androidTestImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module07:module313:module2"))
  implementation(project(":module19:module1:module25:module1"))
  implementation(project(":module23:module01:module23"))
  implementation(project(":module23:module01:module32"))
  implementation(project(":module23:module01:module41"))
  implementation(project(":module23:module01:module53"))
  implementation(project(":module23:module10:module4"))
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
}
