plugins {
  id("com.android.application")
  id("org.jetbrains.kotlin.android")
  id("org.jetbrains.kotlin.kapt")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = true
  }
}
dependencies {
  androidTestImplementation(project(":module07:module183:module05"))
  androidTestImplementation(project(":module07:module183:module08"))
  androidTestImplementation(project(":module07:module224:module4"))
  androidTestImplementation(project(":module07:module358:module4"))
  androidTestImplementation(project(":module07:module540:module1"))
  androidTestImplementation(project(":module08:module28:module3"))
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  androidTestImplementation("androidx.test.espresso:espresso-core:3.3.0")
  androidTestImplementation("androidx.test:rules:1.4.0")
  androidTestImplementation("androidx.test:runner:1.4.0")
  androidTestImplementation("com.google.dagger:dagger:2.39.1")
  androidTestImplementation("junit:junit:4.13.2")
  api(project(":module07:module175:module1"))
  api(project(":module08:module05:module4"))
  api(project(":module08:module28:module5"))
  api("com.google.dagger:dagger:2.39.1")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module01:module01"))
  implementation(project(":module05:module01:module1"))
  implementation(project(":module07:module005:module6"))
  implementation(project(":module07:module011:module2"))
  implementation(project(":module07:module016:module1"))
  implementation(project(":module07:module024:module2"))
  implementation(project(":module07:module024:module4"))
  implementation(project(":module07:module024:module5"))
  implementation(project(":module07:module025:module5"))
  implementation(project(":module07:module031:module2"))
  implementation(project(":module07:module033:module1"))
  implementation(project(":module07:module036:module1"))
  implementation(project(":module07:module066:module1"))
  implementation(project(":module07:module077:module3"))
  implementation(project(":module07:module080:module1"))
  implementation(project(":module07:module091:module3"))
  implementation(project(":module07:module115:module1"))
  implementation(project(":module07:module118:module2"))
  implementation(project(":module07:module120:module1"))
  implementation(project(":module07:module114:module1"))
  implementation(project(":module07:module121:module3"))
  implementation(project(":module07:module132:module2"))
  implementation(project(":module07:module147:module6"))
  implementation(project(":module07:module149:module1"))
  implementation(project(":module07:module169"))
  implementation(project(":module07:module183:module07"))
  implementation(project(":module07:module183:module09"))
  implementation(project(":module07:module189:module4"))
  implementation(project(":module07:module197:module2"))
  implementation(project(":module07:module204:module1"))
  implementation(project(":module07:module213:module1"))
  implementation(project(":module07:module220:module6"))
  implementation(project(":module07:module224:module3"))
  implementation(project(":module07:module260:module3"))
  implementation(project(":module07:module265:module1"))
  implementation(project(":module07:module278:module2"))
  implementation(project(":module07:module289:module4"))
  implementation(project(":module07:module290:module1"))
  implementation(project(":module07:module290:module3"))
  implementation(project(":module07:module293:module3"))
  implementation(project(":module07:module292:module2"))
  implementation(project(":module07:module326:module2"))
  implementation(project(":module07:module332:module1"))
  implementation(project(":module07:module332:module2"))
  implementation(project(":module07:module339:module2"))
  implementation(project(":module07:module358:module2"))
  implementation(project(":module07:module360:module1"))
  implementation(project(":module07:module362:module2"))
  implementation(project(":module07:module363:module3"))
  implementation(project(":module07:module364:module3"))
  implementation(project(":module07:module366:module4"))
  implementation(project(":module07:module361:module3"))
  implementation(project(":module07:module368:module4"))
  implementation(project(":module07:module389:module2"))
  implementation(project(":module07:module403:module1:module1"))
  implementation(project(":module07:module411:module2"))
  implementation(project(":module07:module418"))
  implementation(project(":module07:module422:module1"))
  implementation(project(":module07:module436:module2"))
  implementation(project(":module07:module440:module1"))
  implementation(project(":module07:module452:module2"))
  implementation(project(":module07:module463:module1"))
  implementation(project(":module07:module467:module2"))
  implementation(project(":module07:module468:module2"))
  implementation(project(":module07:module506:module1"))
  implementation(project(":module07:module517:module2"))
  implementation(project(":module07:module522:module3"))
  implementation(project(":module07:module526:module2:module2"))
  implementation(project(":module07:module535:module2"))
  implementation(project(":module07:module544:module2"))
  implementation(project(":module07:module546:module1"))
  implementation(project(":module08:module02:module2"))
  implementation(project(":module08:module03:module1"))
  implementation(project(":module08:module14:module2"))
  implementation(project(":module08:module14:module4"))
  implementation(project(":module08:module18:module1"))
  implementation(project(":module08:module20:module2"))
  implementation(project(":module08:module20:module3"))
  implementation(project(":module08:module23:module1"))
  implementation(project(":module08:module28:module4"))
  implementation(project(":module08:module30"))
  implementation(project(":module08:module52:module4"))
  implementation(project(":module08:module54:module2"))
  implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
  kapt("com.google.dagger:dagger-compiler:2.39.1")
}
