plugins {
  id("com.android.library")
  id("org.jetbrains.kotlin.android")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
    androidResources = true
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  api(project(":module01:module17"))
  api(project(":module07:module015:module3"))
  api(project(":module07:module066:module6"))
  api(project(":module07:module107:module2"))
  api(project(":module07:module111:module3"))
  api(project(":module07:module175:module1"))
  api(project(":module07:module195:module02:module5:module6"))
  api(project(":module07:module208:module8"))
  api(project(":module07:module214:module3"))
  api(project(":module07:module241:module2"))
  api(project(":module07:module243:module8"))
  api(project(":module07:module292:module3"))
  api(project(":module07:module294:module5"))
  api(project(":module07:module374:module3"))
  api(project(":module07:module390:module4"))
  api(project(":module07:module428:module4"))
  api(project(":module08:module06:module3"))
  api(project(":module08:module25:module1:module1"))
  api(project(":module08:module25:module2:module3"))
  api(project(":module08:module25:module5:module5"))
  api(project(":module08:module38:module03:module1"))
  api(project(":module08:module38:module08:module5"))
  api(project(":module08:module38:module09:module6"))
  api(project(":module08:module38:module18:module1"))
  api(project(":module08:module55:module4"))
  api(project(":module19:module1:module01:module3"))
  api(project(":module19:module1:module03:module2"))
  api(project(":module19:module1:module05:module3"))
  api(project(":module19:module1:module08:module3"))
  api(project(":module19:module1:module09:module3"))
  api(project(":module19:module1:module10:module3"))
  api(project(":module19:module1:module12:module2"))
  api(project(":module19:module1:module13:module1"))
  api(project(":module19:module1:module15:module3"))
  api(project(":module19:module1:module16:module3"))
  api(project(":module19:module1:module17:module1"))
  api(project(":module19:module1:module19:module3"))
  api(project(":module19:module1:module22:module3"))
  api(project(":module19:module1:module21:module3"))
  api(project(":module19:module2:module03:module3"))
  api(project(":module19:module2:module05:module4"))
  api(project(":module19:module2:module04:module7"))
  api(project(":module19:module2:module10:module4"))
  api(project(":module19:module2:module14:module7"))
  api(project(":module19:module2:module15:module2"))
  api(project(":module19:module2:module16:module2"))
  api(project(":module19:module2:module17:module2"))
  api(project(":module19:module2:module20:module7"))
  api(project(":module19:module2:module22:module5"))
  api(project(":module19:module2:module21:module2"))
  api(project(":module19:module2:module30:module5"))
  api(project(":module19:module2:module32:module4"))
  api(project(":module19:module2:module36:module5"))
  api(project(":module19:module2:module35:module2"))
  api(project(":module19:module2:module37:module4"))
  api(project(":module19:module2:module34:module8"))
  api(project(":module19:module2:module40:module4"))
  api("com.google.dagger:dagger:2.39.1")
  api("javax.inject:javax.inject:1")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module07:module127"))
  implementation(project(":module07:module139"))
  implementation(project(":module07:module195:module01:module3"))
  implementation(project(":module07:module198:module3"))
  implementation(project(":module07:module215"))
  implementation(project(":module07:module293:module5"))
  implementation(project(":module07:module399"))
  implementation(project(":module07:module547:module3"))
  implementation(project(":module19:module1:module14:module4"))
  implementation(project(":module19:module1:module20:module2"))
  implementation(project(":module19:module1:module26:module3"))
  implementation(project(":module19:module2:module02:module6"))
  implementation(project(":module19:module2:module07:module3"))
  implementation(project(":module19:module2:module21:module2"))
  implementation(project(":module19:module5:module1:module2"))
  implementation(project(":module19:module5:module5"))
  implementation(project(":module19:module5:module8"))
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
  testImplementation(project(":module07:module127"))
  testImplementation(project(":module07:module132:module7"))
  testImplementation(project(":module07:module147:module9"))
  testImplementation(project(":module07:module150:module3"))
  testImplementation(project(":module07:module224:module7"))
  testImplementation(project(":module07:module250"))
  testImplementation(project(":module07:module324:module1"))
  testImplementation(project(":module07:module547:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation(project(":module19:module1:module05:module1"))
  testImplementation(project(":module19:module1:module09:module1"))
  testImplementation(project(":module19:module1:module10:module1"))
  testImplementation(project(":module19:module1:module14:module1"))
  testImplementation(project(":module19:module1:module16:module1"))
  testImplementation(project(":module19:module1:module19:module1"))
  testImplementation(project(":module19:module1:module23:module1"))
  testImplementation(project(":module19:module2:module20:module7"))
  testImplementation(project(":module19:module5:module7"))
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.mockito:mockito-core:3.12.4")
}
