plugins {
  id("com.android.library")
  id("org.jetbrains.kotlin.android")
  id("org.jetbrains.kotlin.kapt")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
    androidResources = true
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  api(project(":module06:module01:module3"))
  api(project(":module06:module05:module01:module2"))
  api(project(":module06:module05:module14:module2"))
  api(project(":module06:module05:module21:module5"))
  api(project(":module06:module05:module22:module3"))
  api(project(":module06:module10:module2"))
  api(project(":module06:module14:module4"))
  api(project(":module07:module095:module6"))
  api(project(":module07:module242:module4"))
  api(project(":module07:module258:module3"))
  api(project(":module07:module390:module4"))
  api(project(":module07:module440:module5"))
  api(project(":module07:module549:module3"))
  api(project(":module07:module564:module1"))
  api(project(":module07:module567:module2"))
  api(project(":module07:module563:module1:module1"))
  api("androidx.appcompat:appcompat:1.3.1")
  api("com.google.dagger:dagger:2.39.1")
  api("com.jakewharton.timber:timber:4.6.1")
  api("io.reactivex.rxjava2:rxjava:2.2.20")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module01:module03"))
  implementation(project(":module01:module10:module1"))
  implementation(project(":module01:module16"))
  implementation(project(":module01:module19"))
  implementation(project(":module06:module02:module3"))
  implementation(project(":module06:module05:module02:module3"))
  implementation(project(":module06:module05:module10:module3"))
  implementation(project(":module06:module05:module18:module3"))
  implementation(project(":module06:module05:module26:module5"))
  implementation(project(":module06:module06:module3"))
  implementation(project(":module06:module09:module2"))
  implementation(project(":module06:module13:module3"))
  implementation(project(":module06:module15:module2"))
  implementation(project(":module06:module17:module3"))
  implementation(project(":module06:module20:module2"))
  implementation(project(":module07:module012"))
  implementation(project(":module07:module047:module3"))
  implementation(project(":module07:module074:module3"))
  implementation(project(":module07:module082:module2"))
  implementation(project(":module07:module084:module3"))
  implementation(project(":module07:module087:module6"))
  implementation(project(":module07:module099"))
  implementation(project(":module07:module102"))
  implementation(project(":module07:module127"))
  implementation(project(":module07:module152:module1"))
  implementation(project(":module07:module193"))
  implementation(project(":module07:module195:module10:module2:module4"))
  implementation(project(":module07:module221:module1:module7"))
  implementation(project(":module07:module297:module3"))
  implementation(project(":module07:module346:module3"))
  implementation(project(":module07:module385:module2"))
  implementation(project(":module07:module387:module2"))
  implementation(project(":module07:module383:module3"))
  implementation(project(":module07:module406:module4"))
  implementation(project(":module07:module463:module2"))
  implementation(project(":module07:module489:module4"))
  implementation(project(":module07:module500:module4"))
  implementation(project(":module07:module534:module1"))
  implementation(project(":module07:module546:module1"))
  implementation(project(":module07:module557"))
  implementation(project(":module08:module36:module5"))
  implementation(project(":module16:module061:module1"))
  implementation("org.jetbrains.kotlin:kotlin-bom:1.6.10")
  kapt("com.google.dagger:dagger-compiler:2.39.1")
  testImplementation(project(":module01:module01"))
  testImplementation(project(":module07:module013:module5"))
  testImplementation(project(":module07:module025:module3"))
  testImplementation(project(":module07:module094:module1"))
  testImplementation(project(":module07:module128"))
  testImplementation(project(":module07:module147:module9"))
  testImplementation(project(":module07:module175:module2"))
  testImplementation(project(":module07:module213:module7"))
  testImplementation(project(":module07:module289:module4"))
  testImplementation(project(":module07:module324:module1"))
  testImplementation(project(":module07:module411:module4"))
  testImplementation(project(":module07:module463:module3"))
  testImplementation(project(":module07:module467:module5"))
  testImplementation(project(":module07:module464:module7"))
  testImplementation(project(":module07:module468:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.6.10")
  testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.0")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.mockito:mockito-core:3.12.4")
}
