plugins {
  id("com.android.library")
  id("org.jetbrains.kotlin.android")
}
android {
  compileSdkVersion = "android-31"
  defaultConfig {
    minSdkVersion(24)
    targetSdkVersion(30)
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions {
    jvmTarget = "1.8"
  }
  buildFeatures {
    buildConfig = false
  }
}
dependencies {
  androidTestImplementation("androidx.annotation:annotation:1.2.0")
  api(project(":module07:module175:module1"))
  api(project(":module08:module42:module6"))
  api("com.google.dagger:dagger:2.39.1")
  api("javax.inject:javax.inject:1")
  compileOnly("androidx.annotation:annotation:1.2.0")
  implementation(project(":module01:module07"))
  implementation(project(":module01:module19"))
  implementation(project(":module05:module30:module9"))
  implementation(project(":module06:module02:module3"))
  implementation(project(":module07:module014:module3"))
  implementation(project(":module07:module025:module6"))
  implementation(project(":module07:module047:module3"))
  implementation(project(":module07:module070"))
  implementation(project(":module07:module076:module4"))
  implementation(project(":module07:module085:module1"))
  implementation(project(":module07:module102"))
  implementation(project(":module07:module105"))
  implementation(project(":module07:module130:module4"))
  implementation(project(":module07:module147:module8"))
  implementation(project(":module07:module153:module3"))
  implementation(project(":module07:module159:module1"))
  implementation(project(":module07:module175:module1"))
  implementation(project(":module07:module178"))
  implementation(project(":module07:module195:module05:module2:module1"))
  implementation(project(":module07:module195:module05:module5:module3"))
  implementation(project(":module07:module195:module06:module1"))
  implementation(project(":module07:module215"))
  implementation(project(":module07:module249"))
  implementation(project(":module07:module258:module3"))
  implementation(project(":module07:module264:module6"))
  implementation(project(":module07:module291:module1"))
  implementation(project(":module07:module297:module3"))
  implementation(project(":module07:module322:module04:module5"))
  implementation(project(":module07:module326:module2"))
  implementation(project(":module07:module329:module1"))
  implementation(project(":module07:module339:module4"))
  implementation(project(":module07:module342:module1"))
  implementation(project(":module07:module338:module1"))
  implementation(project(":module07:module344:module4"))
  implementation(project(":module07:module345:module6"))
  implementation(project(":module07:module368:module6"))
  implementation(project(":module07:module370:module3"))
  implementation(project(":module07:module373:module3"))
  implementation(project(":module07:module374:module3"))
  implementation(project(":module07:module375:module4"))
  implementation(project(":module07:module376:module1:module5"))
  implementation(project(":module07:module378:module5"))
  implementation(project(":module07:module393:module2"))
  implementation(project(":module07:module394:module1"))
  implementation(project(":module07:module406:module4"))
  implementation(project(":module07:module415:module4"))
  implementation(project(":module07:module416:module5"))
  implementation(project(":module07:module425:module1"))
  implementation(project(":module07:module431:module1"))
  implementation(project(":module07:module483:module5"))
  implementation(project(":module07:module500:module4"))
  implementation(project(":module07:module505:module1"))
  implementation(project(":module07:module514:module5"))
  implementation(project(":module07:module522:module4"))
  implementation(project(":module07:module549:module3"))
  implementation(project(":module07:module550:module1"))
  implementation(project(":module07:module561:module1"))
  implementation(project(":module07:module562:module2"))
  implementation(project(":module07:module566:module2"))
  implementation(project(":module07:module567:module2"))
  implementation(project(":module08:module09:module3"))
  implementation(project(":module08:module19:module3"))
  implementation(project(":module08:module39:module2"))
  implementation(project(":module08:module40:module5"))
  implementation(project(":module14:module2:module2"))
  implementation(project(":module16:module028:module1"))
  implementation(project(":module26:module4:module1"))
  implementation("io.reactivex.rxjava2:rxjava:2.2.20")
  implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
  testImplementation(project(":module07:module013:module5"))
  testImplementation(project(":module07:module068"))
  testImplementation(project(":module07:module132:module7"))
  testImplementation(project(":module07:module147:module9"))
  testImplementation(project(":module07:module150:module3"))
  testImplementation(project(":module07:module213:module7"))
  testImplementation(project(":module07:module224:module7"))
  testImplementation(project(":module07:module324:module1"))
  testImplementation(project(":module07:module374:module4"))
  testImplementation(project(":module07:module411:module4"))
  testImplementation(project(":module07:module447:module2"))
  testImplementation(project(":module07:module464:module7"))
  testImplementation(project(":module07:module522:module1"))
  testImplementation(project(":module07:module542:module3"))
  testImplementation(project(":module07:module547:module4"))
  testImplementation(project(":module07:module549:module4"))
  testImplementation(project(":module07:module567:module3"))
  testImplementation(project(":module14:module2:module3"))
  testImplementation("androidx.test:monitor:1.5.0")
  testImplementation("com.google.truth:truth:1.1.3")
  testImplementation("junit:junit:4.13.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.7.20")
  testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.0")
  testImplementation("org.mockito.kotlin:mockito-kotlin:3.2.0")
  testImplementation("org.mockito:mockito-core:3.12.4")
  testImplementation("org.robolectric:robolectric:4.7.3")
  testImplementation("org.threeten:threetenbp:1.6.0")
}
